version: "3.9"
services:
  backend:
    build: ./backend
    container_name: bookstore-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: bookstore-frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend


  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: anhmuoi137
      MYSQL_DATABASE: bookstores
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
