services:
  frontend:
    build: ./bookstore-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=anhmuoi137
      - DB_NAME=bookstores

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: anhmuoi137
      MYSQL_DATABASE: bookstores
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
